### ISSUE TITLE
Update Docker Compose

### ISSUE THREAD

**Issue by czadikem** [overte-org/overte-domain-server-docker#14]
The Docker compose file is outdated, update it to not have version as well as have the correct docker image to pull 
```
services:
  overte-server:
    image: overte/overte-server:latest
    container_name: overte-server
    restart: unless-stopped
    # Make sure 40102 is open on your router and computer, should be TCP/UDP
    expose:
      - "40100-40102"
    ports:
      - "40100-40102:40100-40102"
      - "40100-40102:40100-40102/udp"
      - "48000-48006:48000-48006/udp"
    volumes:
      - "./logs:/var/log"
      - "./data:/root/.local/share/Overte"
```
